spring.application.name=smartinventory
server.port=8090

server.servlet.context-path=/api

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


# # ── Base de datos H2 (desarrollo) ──────────────────────────────────────────
# spring.datasource.url=jdbc:h2:mem:smartinventory
# spring.datasource.driver-class-name=org.h2.Driver
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.datasource.username=admin
# spring.datasource.password=admin

# # Consola web de H2 — accesible en http://localhost:8090/api/h2-console
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# # JPA crea las tablas al arrancar y las elimina al detener el servidor
# spring.jpa.hibernate.ddl-auto=create-drop

# # Muestra el SQL que genera Hibernate en el log
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# ── Base de datos PostgreSQL ──────────────────────7──────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5439/smartinventory
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# update — actualiza el esquema sin borrar datos existentes
spring.jpa.hibernate.ddl-auto=update

# Muestra el SQL generado por Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging.level.ec.org.cedia.smartinventory=WARN
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%level] %logger{36} - %msg%n