spring.application.name=smartinventory
spring.profiles.active=dev
server.port=8090

server.servlet.context-path=/api

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
logging.pattern.console=%d{HH:mm:ss} [%level] %logger{36} - %msg%n
